import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  const result = await req.json()

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; padding: 40px; color: #1f1f1f; }
  h1 { font-size: 28px; margin-bottom: 4px; }
  .meta { color: #5f6368; font-size: 13px; margin-bottom: 32px; }
  .score { font-size: 64px; font-weight: bold; color: ${
    result.riskLevel === 'CRITICAL' ? '#c5221f' :
    result.riskLevel === 'HIGH' ? '#e37400' :
    result.riskLevel === 'MODERATE' ? '#b06000' : '#137333'
  }; }
  .level { font-size: 24px; font-weight: 600; margin-bottom: 32px; color: ${
    result.riskLevel === 'CRITICAL' ? '#c5221f' : '#1f1f1f'
  }; }
  .summary-box { background: #f8f9fa; border-left: 4px solid #1a73e8; padding: 16px; margin-bottom: 32px; font-size: 14px; line-height: 1.6; }
  .stats { display: flex; gap: 20px; margin-bottom: 32px; }
  .stat { text-align: center; padding: 12px 20px; border: 1px solid #e8eaed; border-radius: 8px; }
  .stat-n { font-size: 28px; font-weight: bold; }
  .stat-l { font-size: 12px; color: #5f6368; }
  .finding { margin-bottom: 20px; padding: 16px; border: 1px solid #e8eaed; border-radius: 8px; page-break-inside: avoid; }
  .chip { display: inline-block; padding: 2px 10px; border-radius: 20px; font-size: 11px; font-weight: bold; margin-bottom: 8px; }
  .chip-CRITICAL { background: #fce8e6; color: #c5221f; }
  .chip-HIGH { background: #fef3e2; color: #e37400; }
  .chip-MEDIUM { background: #e6f4ea; color: #137333; }
  .chip-LOW { background: #e8f0fe; color: #1a73e8; }
  .finding-title { font-size: 15px; font-weight: 600; margin-bottom: 6px; }
  .finding-desc { font-size: 13px; color: #5f6368; margin-bottom: 8px; }
  .fix-box { background: #f8f9fa; padding: 10px; border-radius: 6px; font-size: 12px; }
  .fix-label { font-weight: 600; color: #137333; font-size: 12px; margin-bottom: 4px; }
  pre { background: #1f1f1f; color: #e8f5e9; padding: 12px; border-radius: 6px; font-size: 11px; overflow-x: auto; margin-top: 8px; white-space: pre-wrap; }
  .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e8eaed; font-size: 12px; color: #80868b; }
</style>
</head>
<body>
  <h1>VulnLens Security Report</h1>
  <div class="meta">
    Target: ${result.target} &nbsp;&middot;&nbsp; 
    Scan type: ${result.scanType} &nbsp;&middot;&nbsp; 
    Date: ${new Date(result.timestamp).toLocaleString()}
  </div>

  <div class="score">${result.riskScore}</div>
  <div class="level">${result.riskLevel} RISK</div>

  ${result.aiSummary ? `<div class="summary-box"><strong>AI Security Summary:</strong><br>${result.aiSummary}</div>` : ''}

  <div class="stats">
    <div class="stat"><div class="stat-n" style="color:#c5221f">${result.summary.critical}</div><div class="stat-l">Critical</div></div>
    <div class="stat"><div class="stat-n" style="color:#e37400">${result.summary.high}</div><div class="stat-l">High</div></div>
    <div class="stat"><div class="stat-n" style="color:#b06000">${result.summary.medium}</div><div class="stat-l">Medium</div></div>
    <div class="stat"><div class="stat-n" style="color:#137333">${result.summary.low}</div><div class="stat-l">Low</div></div>
  </div>

  <h2 style="margin-bottom:16px">Findings (${result.findings.length})</h2>
  ${result.findings.filter((f: any) => f.severity !== 'INFO').map((f: any) => `
    <div class="finding">
      <span class="chip chip-${f.severity}">${f.severity}</span>
      <div class="finding-title">${f.title}</div>
      <div class="finding-desc">${f.description}</div>
      <div class="fix-box">
        <div class="fix-label">Fix: </div>
        ${f.recommendation}
        ${f.fixSnippet ? `<pre>${f.fixSnippet.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</pre>` : ''}
      </div>
      ${f.cve ? `<div style="font-size:11px;color:#80868b;margin-top:6px">CVE: ${f.cve}</div>` : ''}
    </div>
  `).join('')}

  <div class="footer">
    Generated by VulnLens v1.2.0 &nbsp;&middot;&nbsp; 
    Scan ID: ${result.scanId || 'N/A'} &nbsp;&middot;&nbsp;
    OSV.dev vulnerability database
  </div>
</body>
</html>`

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `attachment; filename="vulnlens-report-${Date.now()}.html"`,
    }
  })
}
